### ISSUE TITLE
Docker-Compose getting error

### ISSUE THREAD

**Issue by SHAMUH2020** [codespaces-io/codespaces#17]
docker-compose up -d  getting ERROR: could not find plugin bridge in v1 plugin registry: plugin not found.

**Comment by SHAMUH2020** [comment]
@initcron Could you please help me with this?

**Comment by ppdouble** [comment]
like this ?:

```
networks:
      nacos_net:
        ipam:
          driver: bridge
          config:
            - subnet: "10.0.2.0/24"
```

change `driver: bridge` as `driver: default`. then you will get a `bridge` network
